$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: hello_pipeline_abc
compute: azureml:eunsang-ml-research

inputs:
  hello_string_top_level_input: "hello world"

jobs:
  a:
    command: echo hello ${{inputs.hello_string}}
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    inputs:
      hello_string: ${{parent.inputs.hello_string_top_level_input}}

  b:
    command: echo "world" >> ${{outputs.world_output}}/world.txt
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    outputs:
      world_output:

  c:
    command: echo ${{inputs.world_input}}/world.txt
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    inputs:
      world_input: ${{parent.jobs.b.outputs.world_output}}

  d:
    command: |
      # Authenticate with Azure
      az login --service-principal -u {YOUR_CLIENT_ID} -p {YOUR_CLIENT_SECRET} --tenant {YOUR_TENANT_ID}
      
      # Verify authentication
      az account show
      
      # Example: List datasets in the Azure ML workspace
      az ml data list --workspace-name inbrein-azure-ml-research-eunsang --resource-group inbrein-azure-ml-research
    environment:
      image: eunsangacr.azurecr.io/azureml-with-azcli:latest  # Referencing the ACR image