
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: scheduled_pipeline
compute: azureml:eunsang-ml-research

jobs:
  prepare_dataset:
    command: |
      # Authenticate with Azure
      az login --service-principal -u {YOUR_CLIENT_ID} -p {YOUR_CLIENT_SECRET} --tenant {YOUR_TENANT_ID}
      
      # Create dataset 
      az ml data create --name iris-dataset \
        --path /app/datasets/iris.csv \
        --type uri_file \
        --workspace-name inbrein-azure-ml-research-eunsang \
        --resource-group inbrein-azure-ml-research
      
      # Example: List datasets in the Azure ML workspace
      az ml data list --workspace-name inbrein-azure-ml-research-eunsang --resource-group inbrein-azure-ml-research
    environment:
      image: eunsangacr.azurecr.io/azureml-with-azcli:latest  # Referencing the ACR image
